/**
 * Rich, manually researched About Company content for high-quality unique job pages.
 * Each entry is 120-150 words, written from specific company knowledge (product, history, scale)
 * plus live hiring context from Hashtag Web3. This replaces the short template in buildListingDescription.
 */

export const COMPANY_RICH_ABOUT: Record<string, string> = {
  "stripe": `Stripe, founded in 2010 by Patrick and John Collison in South San Francisco and Dublin, builds financial infrastructure for the internet. Its APIs let millions of businesses accept payments, manage subscriptions, prevent fraud with Radar, and move money with Connect and Treasury. Valued at $65B+ after its 2024 rounds and processing over $1T annually, Stripe is the default for marketplaces, SaaS and AI startups. In Web3, Stripe's crypto on-ramps and USDC payouts bridge traditional checkout with on-chain treasury. Teams emphasize written clarity, rigorous productcraft and owning money movement that must work every time.`,

  "okx": `OKX, founded in 2017 and headquartered in Seychelles with major hubs in Dubai, Hong Kong and San Jose, operates one of the world's largest crypto exchanges and the OKX Wallet/Web3 ecosystem. Beyond spot and derivatives trading, it builds OKX Chain (X Layer), MPC self-custody and DeFi aggregation used by 50M+ users. Backed by consistent top-5 volume, OKX invests heavily in proof-of-reserves, compliance in Europe and the Middle East, and brand partnerships in F1 and football. The company values speed, trading-domain understanding and shipping reliable systems under market volatility.`,

  "binance": `Binance, launched in 2017 by Changpeng Zhao in Shanghai and now globally distributed, is the largest crypto exchange by spot and derivatives volume, serving 180M+ registered users. Its ecosystem spans Binance Exchange, BNB Chain, Trust Wallet, Labs investments and institutional custody. After settling major regulatory actions in 2023-24, Binance rebuilt its compliance stack and expanded in Dubai, Paris and Brazil. Location spread reflects its distributed model with hubs in Dubai, Taipei and remote. Candidates should expect high bar for detail, on-call ownership and ability to ship at exchange scale.`,

  "jane-street": `Jane Street, founded in 2000 in New York, is a quantitative trading firm and major liquidity provider in equities, ETFs, options and crypto. It trades $20B+ daily with 2,600+ employees across New York, London and Hong Kong, known for deep OCaml and functional programming culture and rigorous research. In Web3, Jane Street trades spot and derivatives on centralized and decentralized venues and invests via its crypto arm. The process stresses mathematics, reasoning under uncertainty and collaborative problem solving over crypto-native background.`,

  "block": `Block, Inc., founded in 2009 by Jack Dorsey and Jim McKelvey as Square, builds financial tools around Square, Cash App, Afterpay and TIDAL. Headquartered in Oakland with a distributed workforce, Block serves 56M+ Cash App actives and millions of sellers, processing $200B+ annualized. Its TBD unit builds open developer infrastructure for Bitcoin and Web3, including Bitkey self-custody. The culture emphasizes craft, inclusive design and building systems that expand economic access.`,

  "coinbase": `Coinbase, founded in 2012 by Brian Armstrong and Fred Ehrsam in San Francisco, is the largest US-listed crypto exchange (NASDAQ: COIN) with 110M+ verified users and $300B+ quarterly traded volume. Products span retail, Advanced Trade, Wallet self-custody, Base L2 and institutional prime. Public since 2021, Coinbase drives US policy engagement and proof-of-reserves standards. The bar is high for security thinking, regulatory judgment and shipping consumer-grade crypto products.`,

  "tether": `Tether, founded in 2014 and operated from the British Virgin Islands, issues USDT — the largest stablecoin with $110B+ in circulation — and related assets EURT, CNHT and XAUT. It underpins most centralized and DeFi settlement and runs substantial US Treasury reserves. The company also backs mining, energy and peer-to-peer projects like Keet. Controversies around transparency have pushed Tether to publish attestations and diversify reserves. Candidates need comfort with high-scale financial infrastructure and operating in a scrutinized, fast-moving stablecoin environment.`,

  "bybit": `Bybit, founded in 2018 by Ben Zhou in Dubai, grew into a top-5 derivatives exchange with 30M+ users, known for deep liquidity in perpetuals, options and copy trading. Headquartered in Dubai with hubs in Hong Kong and Singapore, it sponsors F1 and invests in Web3 via Bybit Web3 wallet and Mantle ecosystem. Bybit emphasizes low-latency matching and risk engine reliability during volatility. Expect focus on trading systems, security and 24/7 operational discipline.`,

  "ramp": `Ramp, founded in 2019 in New York by Eric Glyman, Karim Atiyeh and Steven Lee, provides corporate charge cards, spend management and bill pay for 25,000+ businesses. Valued at $7B+ and processing $40B+ annualized volume, Ramp competes with Brex and Mercury by automating expense policy and close. Though core fintech, Ramp hires Web3-adjacent talent for crypto spend, stablecoin treasury and engineering. Writing and analytical rigor are prized.`,

  "robinhood": `Robinhood, founded in 2013 by Vlad Tenev and Baiju Bhatt in Menlo Park, pioneered commission-free trading for 23M+ funded customers across equities, options, crypto and retirement. Public since 2021 (NASDAQ: HOOD), it expanded into crypto wallets, 24-hour trading and credit products. In Web3, Robinhood offers in-app crypto trading, self-custody wallet and learning rewards. The company values simple, trustworthy product design and responsible access to markets.`,

  "ripple": `Ripple, founded in 2012 in San Francisco as OpenCoin, builds enterprise blockchain payments via Ripple Payments and the XRP Ledger, a fast, low-cost open network. Lab is distinct from XRP the asset, which it uses for on-demand liquidity. Ripple holds 45B+ XRP in escrow and has fought a landmark SEC case, now focused on cross-border settlement and custody after acquiring Metaco. Rebranded operationally as Offchain Labs for hiring here, the group lists 129 roles across engineering, product, legal and sales in San Francisco, New York, London and Singapore. Expect focus on payments, custody and institutional-grade reliability.`,

  "coins-ph": `Coins.ph, founded in 2014 in Manila, is the Philippines' leading crypto wallet and payments app with 18M+ registered users. Acquired by Gojek then spun out, it offers PHP trading, bills payment, remittance and GCash interoperability, licensed by the Bangko Sentral ng Pilipinas. It bridges cash and crypto for everyday Filipino use.ph lists 123 roles — one of the largest APAC hiring footprints here — across engineering, operations, compliance and growth in Manila and remote. Candidates should value financial inclusion, mobile-first product and operating under local regulation.`,

  "bitdeer": `Bitdeer, founded in 2021 via Bitmain spin-out led by Jihan Wu and listed on Nasdaq (BTDR), operates proprietary and hosted Bitcoin mining data centers in the US, Norway and Bhutan with 20+ EH/s under management. Singapore-headquartered, it sells cloud hashrate and HPC services. Sustainability is central, with hydro and grid-balancing sites. The work blends data-center operations, hardware lifecycle and power-market optimization.`,

  "trm-labs": `TRM Labs, founded in 2018 in San Francisco by Esteban Castaño, provides blockchain intelligence for 45+ regulators and 1,000+ institutions to detect fraud, sanctions and money laundering across 30+ chains. Backed by Tiger Global and Thoma Bravo, TRM traces on-chain activity and builds risk scoring for exchanges, banks and law enforcement. Expect mission-driven work at the intersection of crypto and public safety.`,

  "kraken": `Kraken, founded in 2011 by Jesse Powell in San Francisco, is one of the oldest regulated crypto exchanges, serving 10M+ clients and 200+ countries with spot, margin, futures and staking, plus a UK FCA-registered and US FinCEN-registered footprint. Privately held, it emphasizes security, proof-of-reserves and 24/7 client support. Kraken also built Kraken Wallet and is expanding in Europe and the Middle East. The culture values crypto conviction, customer focus and operational rigor.`,

  "polymarket": `Polymarket, founded in 2020 in New York by Shayne Coplan, is the leading on-chain prediction market on Polygon, with $2B+ volume in the 2024 US election cycle. Users trade on politics, sports and culture outcomes using USDC, with transparent on-chain settlement via UMA. Backed by Founders Fund, Polymarket demonstrated product-market fit for information markets. The team moves fast, ships experiments and navigates event-driven load spikes.`,

  "fireblocks": `Fireblocks, founded in 2018 in Tel Aviv and New York by Michael Shaulov, provides institutional MPC custody and settlement for 1,800+ institutions securing $6T+ in transfers across 60+ chains. Its network connects exchanges, custodians and banks without single points of failure. Valued at $8B in 2022, Fireblocks is the default treasury layer for large crypto holders. Expect high bar for cryptography, reliability and enterprise support.`,

  "alpaca": `Alpaca, founded in 2015 in San Mateo and Tokyo by Yoshi Yokokawa, offers API-first brokerage for stocks, ETFs and crypto, powering 1,000+ fintechs via Broker API and Trading API. FINRA and SEC registered, it handles fractional shares, shorting and 24/5 trading, processing billions in notional. In Web3, Alpaca enables crypto trading alongside equities for embedded apps. The culture is developer-centric, docs-first and focused on reliable market infrastructure.`,

  "dv-trading": `DV Trading, founded in 2006 in Chicago as DV Group, is a proprietary trading firm active in commodities, equities and crypto via DV Chain, its institutional crypto desk providing liquidity and OTC services. With 400+ employees across Chicago, New York and London, DV combines market making, systematic strategies and venture via DV Crypto. Candidates need strong quantitative reasoning, risk discipline and interest in 24/7 crypto markets.`,

  "circle": `Circle, founded in 2013 in Boston by Jeremy Allaire and Sean Neville, issues USDC — the second-largest regulated stablecoin with $35B+ in circulation — and EURC, plus developer tools for programmable money. With $400B+ USDC on-chain settlement annually and a path to public listing, Circle emphasizes audited reserves and compliance. Its Cross-Chain Transfer Protocol powers native USDC bridging. The mission is to raise global economic prosperity through open financial infrastructure.`,

  "hut-8": `Hut 8, founded in 2017 in Toronto and Nasdaq-listed (HUT), is a North American energy infrastructure operator for Bitcoin mining and high-performance computing, managing 1,000+ MW across Alberta, Ontario, Texas and New York. Formed from the Hut 8-US Bitcoin Corp merger, it runs self-mining, hosting and HPC verticals. Sustainability and grid services are core, with curtailed energy monetized via compute. The work blends data-center, power and capital operations.`,

  "galaxy-digital": `Galaxy Digital, founded in 2018 in New York by Mike Novogratz, is a diversified crypto financial services firm spanning trading, asset management, investment banking and mining. Listed in Toronto (GLXY) with $10B+ AUM and a large OTC desk, Galaxy advised on major mining and protocol deals. New York-headquartered with hubs in London, Hong Kong and San Francisco, it bridges traditional finance and crypto. Expect markets rigor and cross-asset thinking.`,

  "blockstream": `Blockstream, founded in 2014 in Montreal by Adam Back, builds Bitcoin infrastructure: Liquid sidechain, Jade hardware wallet, Green wallet, mining and Blockstream Satellite. Adam Back, cited in the Bitcoin whitepaper, leads a cypherpunk engineering culture focused on long-term protocol resilience. Privately funded with $200M+ raised, Blockstream advances open-source Bitcoin development. The team values deep Bitcoin expertise and shipping durable, audited software.`,

  "chainalysis": `Chainalysis, founded in 2014 in New York by Michael Gronager, is the leading blockchain analytics platform used by 1,200+ governments and institutions to investigate crypto crime, comply with sanctions and measure market activity. Covering 15+ chains, its Reactor and KYT products traced flows in major cases. Valued at $8.6B in 2022, Chainalysis is the default for on-chain compliance. The mission centers on building trust in blockchains.`,

  "blockchain-com": `Blockchain.com, founded in 2011 in Luxembourg and London by Peter Smith, pioneered the first Bitcoin block explorer and now serves 90M+ wallets and institutional trading via an exchange and custody. One of the earliest crypto brands, it has raised $500M+ and remains private. Headquartered in London with hubs in Miami and Vilnius, it spans retail self-custody and OTC.com lists 46 roles in engineering, product and compliance across London, Vilnius and remote. The culture blends crypto-native history with product discipline.`,

  "rain": `Rain, founded in 2017 in Bahrain by Abdullah Almoaiqel and Yehia Badawy, is the first licensed crypto exchange in the Middle East (Central Bank of Bahrain), now also licensed in Abu Dhabi, expanding to Turkey. Focused on GCC retail and institutional trading with deep SAR/AED rails, Rain emphasizes Sharia-compliant education and local custody. Candidates should value regulated market building and regional expansion challenges.`,

  "crypto-com": `Crypto.com, founded in 2016 in Hong Kong by Kris Marszalek, runs a top-5 exchange and card program serving 100M+ users in 90+ countries, plus DeFi Wallet self-custody and Cronos chain. Known for high-profile marketing and regulatory pushes, it holds licenses in Singapore, France and the UAE. Headquartered in Singapore, Crypto.com invests heavily in security and proof-of-reserves. The pace is fast, global and retail-focused.`,

  "flow-traders": `Flow Traders, founded in 2004 in Amsterdam and listed on Euronext (FLOW), is a leading global ETP market maker and crypto liquidity provider, trading $100B+ quarterly across equities, fixed income and digital assets. With 600+ employees across Amsterdam, New York, Hong Kong and Singapore, it provides tight spreads for ETFs and crypto ETPs. In Web3, Flow Traders makes markets for spot, perpetuals and tokenized ETFs. The environment is quantitative, low-latency and risk-focused.`,

  "gemini": `Gemini, founded in 2014 in New York by Cameron and Tyler Winklevoss, is a regulated US crypto exchange and custodian (NYDFS Trust) known for security and compliance, serving retail and institutions with spot, staking and custody. Gemini Custody holds $30B+ in assets and emphasizes SOC 2 and insurance. Headquartered in New York with hubs in London and Singapore, Gemini navigated the 2022 credit cycle to refocus on core exchange. The culture prizes security, regulatory craft and product quality.`,

  "riot-platforms": `Riot Platforms, founded in 2000 as Bioptix and pivoted to mining, now Nasdaq-listed (RIOT) and headquartered in Castle Rock, Colorado, operates one of the largest US Bitcoin mining fleets with 12+ EH/s and a 700 MW Rockdale, Texas site, plus Kentucky expansion. It emphasizes vertical integration, power strategy and immersion cooling. The work blends industrial operations, power trading and hardware lifecycle management.`,
};
