'use client';
import { useEffect, useState } from 'react';
import { Plus, Trash2 } from 'lucide-react';
import { calendarDay, schengenDays, nextSchengenCapacity, tripError, type Trip } from '@/lib/nomads/calculations';
import { Field, inputStyle, buttonStyle, MetricCard, NomadPanel, SourceNote } from './ui';

const STORAGE_KEY = 'hw3-nomad-schengen-v1';
export function SchengenTracker({ today }: { today: string }) {
  const [trips, setTrips] = useState<Trip[]>([{ id: 'first', start: '', end: '' }]);
  const [asOf, setAsOf] = useState(today), [save, setSave] = useState(false), [ready, setReady] = useState(false), [storageError, setStorageError] = useState(false);
  const [undo, setUndo] = useState<Trip[] | null>(null);
  useEffect(() => {
    try { const raw = localStorage.getItem(STORAGE_KEY); if (raw) { const data: unknown = JSON.parse(raw); if (Array.isArray(data) && data.length <= 100 && data.every(trip => trip && typeof trip.id === 'string' && typeof trip.start === 'string' && typeof trip.end === 'string')) { setTrips(data.length ? data : [{ id: 'first', start: '', end: '' }]); setSave(true); } } } catch { setStorageError(true); }
    setReady(true);
  }, []);
  useEffect(() => { if (!ready) return; try { if (save) localStorage.setItem(STORAGE_KEY, JSON.stringify(trips)); else localStorage.removeItem(STORAGE_KEY); } catch { setStorageError(true); } }, [trips, save, ready]);
  const days = schengenDays(trips, asOf), remaining = Math.max(0, 90 - days), next = days >= 90 ? nextSchengenCapacity(trips, asOf) : null;
  const invalid = trips.filter(trip => (trip.start || trip.end) && tripError(trip));
  const update = (id: string, field: 'start' | 'end', value: string) => setTrips(current => current.map(trip => trip.id === id ? { ...trip, [field]: value } : trip));
  return <div><div className="mb-6 grid gap-3 sm:grid-cols-3"><Field label="Check the rolling window on" className="justify-center rounded-lg border border-border/70 bg-card p-4"><input type="date" className={inputStyle} value={asOf} onChange={event => setAsOf(event.target.value)} /></Field><dl className="grid grid-cols-2 gap-3 sm:col-span-2"><MetricCard label="Days used" value={days} detail="Unique days in the previous 180 days" /><MetricCard label={days > 90 ? 'Days above the limit' : 'Days remaining'} value={days > 90 ? days - 90 : remaining} detail="Against the 90-day allowance" /></dl></div>{calendarDay(asOf) === null && <p role="alert" className="mb-4 text-sm text-destructive">Select a valid check date.</p>}
    {next && <p className="mb-5 rounded-xl border bg-muted/20 p-4 text-sm">The next date with capacity for at least one day is <strong>{next}</strong>, based on the trips entered.</p>}
    <NomadPanel><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold">Your trips</h2><button className={buttonStyle} disabled={trips.length >= 100} onClick={() => setTrips(current => [...current, { id: crypto.randomUUID(), start: '', end: '' }])}><Plus className="h-4 w-4" aria-hidden />Add trip</button></div><div className="space-y-4">{trips.map((trip, index) => <div key={trip.id} className="rounded-lg border p-3"><div className="grid items-end gap-3 sm:grid-cols-[1fr_1fr_auto]"><Field label={`Trip ${index + 1} arrival`}><input className={inputStyle} type="date" value={trip.start} onChange={event => update(trip.id, 'start', event.target.value)} /></Field><Field label={`Trip ${index + 1} departure`}><input className={inputStyle} type="date" value={trip.end} onChange={event => update(trip.id, 'end', event.target.value)} /></Field><button aria-label={`Remove trip ${index + 1}`} className={buttonStyle} onClick={() => setTrips(current => current.filter(item => item.id !== trip.id))}><Trash2 className="h-4 w-4" aria-hidden /><span className="sm:sr-only">Remove trip</span></button></div>{(trip.start || trip.end) && tripError(trip) && <p role="alert" className="mt-2 text-xs text-destructive">{tripError(trip)}</p>}</div>)}</div><div className="mt-6 flex flex-wrap items-center justify-between gap-4"><label className="inline-flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={save} onChange={event => setSave(event.target.checked)} className="h-4 w-4 accent-current" />Save trips on this device</label><div className="flex gap-3"><button className={buttonStyle} onClick={() => { setUndo(trips); setTrips([{ id: crypto.randomUUID(), start: '', end: '' }]); }}>Clear trips</button>{undo && <button className={buttonStyle} onClick={() => { setTrips(undo); setUndo(null); }}>Undo</button>}</div></div><p className="mt-2 text-xs text-muted-foreground">Calculations stay in your browser. Saving is optional and does not upload your trips.</p>{storageError && <p className="mt-2 text-xs text-muted-foreground">Browser storage is unavailable. You can still use the calculator in this session.</p>}</NomadPanel>
    {invalid.length > 0 && <p aria-live="polite" className="mt-4 text-sm text-muted-foreground">Complete or correct {invalid.length} trip{invalid.length === 1 ? '' : 's'} to include them in the calculation.</p>}
    <SourceNote>Arrival and departure days count. Overlapping trips count each calendar day once. The window includes the selected check date and the preceding 179 days; visa-specific exceptions are outside this calculator.</SourceNote>
  </div>;
}
