
import { MetadataRoute } from 'next';

const siteUrl = 'https://hashtagweb3.com';

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const articleSlugs = [
    "10-big-ideas-in-web3-for-2025",
    "10-essential-skills-for-web3",
    "a-day-in-the-life-of-a-defi-quant",
    "a-deep-dive-into-rollups-for-ethereum-scaling",
    "a-guide-to-verifiable-credentials-in-decentralized-identity",
    "account-abstraction-explained",
    "ai-accountability-governance-models",
    "ai-and-web3-engineering-careers",
    "ai-and-web3-hybrid-careers",
    "ai-driven-agency-from-automation-to-autonomy",
    "an-introduction-to-foundry-the-modern-solidity-toolkit",
    "answering-why-web3-crafting-your-personal-narrative-for-interviews",
    "becoming-a-web3-decentralized-storage-expert",
    "becoming-a-web3-digital-content-monetization-specialist",
    "becoming-a-web3-technical-writer",
    "best-web3-jobs-for-non-developers",
    "beyond-the-code",
    "blockchain-sharding-scalability",
    "breaking-into-blockchain-devops",
    "breaking-into-web3-a-guide-for-non-technical-professionals",
    "breaking-into-web3-game-development-jobs",
    "building-a-career-as-a-web3-blockchain-infrastructure-engineer",
    "building-a-network-for-web3-career-opportunities",
    "building-career-paths-for-web3-privacy-engineers",
    "building-responsible-ai-systems",
    "building-web3-portfolio",
    "building-your-first-dapp-on-solana-with-rust",
    "career-opportunities-for-web3-blockchain-networking-engineers",
    "cbdc",
    "challenges-in-agentic-ai-governance",
    "china-digital-yuan-ecny",
    "closing-the-web3-talent-gap",
    "common-smart-contract-vulnerabilities-explained",
    "common-take-home-assignments-for-web3-developer-roles",
    "creating-dynamic-nfts-a-step-by-step-guide",
    "crypto-etfs-explained",
    "crypto-marketing-jobs",
    "crypto-taxes-guide",
    "decentralized-identity-explained",
    "decoding-web3-salary",
    "defi-careers",
    "does-web3-pay-well",
    "elon-musk-on-web3",
    "essential-skills-for-web3-developers",
    "essential-web3-developer-tools",
    "exploring-career-opportunities-as-a-web3-blockchain-validator",
    "exploring-career-paths-for-web3-compliance-officers",
    "exploring-careers-in-web3-oracles-and-data-feeds",
    "exploring-cosmos-sdk-for-web3-development",
    "exploring-opportunities-in-web3-real-estate-tokenization",
    "exploring-the-future-of-web3-jobs",
    "exploring-web3-careers-in-decentralized-autonomous-finance",
    "exploring-web3-gaming",
    "exploring-web3-project-manager-career-paths",
    "formal-verification-smart-contract-security",
    "freelance-vs-full-time-web3-career",
    "from-side-hustle-to-career",
    "future-of-blockchain-interoperability-with-polkadot",
    "future-of-work-in-the-metaverse",
    "future-of-work-in-web3",
    "gas-optimization-techniques-for-solidity-developers",
    "guide-to-layer-2s",
    "guide-to-stablecoins",
    "highest-paying-web3-jobs",
    "hiring-for-a-dao",
    "how-dag-based-blockchains-differ-from-traditional-chains",
    "how-formal-verification-improves-smart-contract-security",
    "how-homomorphic-encryption-powers-web3-privacy",
    "how-mev-impacts-web3-networks-and-developers",
    "how-sharding-improves-blockchain-scalability",
    "how-to-become-a-blockchain-developer",
    "how-to-become-a-web3-blockchain-marketing-strategist",
    "how-to-become-a-web3-blockchain-patent-and-ip-expert",
    "how-to-become-a-web3-legal-consultant",
    "how-to-become-a-web3-liquidity-provider-in-decentralized-finance",
    "how-to-become-a-web3-nft-artist",
    "how-to-become-a-web3-smart-contract-developer",
    "how-to-become-a-web3-staking-specialist",
    "how-to-become-a-web3-yield-farming-analyst",
    "how-to-break-into-web3-cryptographic-research-and-development",
    "how-to-break-into-web3-dao-governance-consulting",
    "how-to-break-into-web3-smart-contract-auditing",
    "how-to-build-a-career-as-a-web3-decentralized-exchange-developer",
    "how-to-build-a-public-on-chain-developer-brand",
    "how-to-build-a-simple-amm-on-an-l2",
    "how-to-build-a-strong-web3-portfolio",
    "how-to-build-a-web3-resume-that-stands-out",
    "how-to-choose-a-crypto-wallet",
    "how-to-contribute-to-daos-and-get-paid",
    "how-to-get-a-job-in-defi-with-no-experience",
    "how-to-get-a-web3-job-with-no-experience",
    "how-to-get-into-web3-cryptocurrency-taxation-and-accounting",
    "how-to-get-started-as-a-web3-cryptocurrency-venture-capital-analyst",
    "how-to-get-started-as-a-web3-nft-marketplace-developer",
    "how-to-get-started-as-a-web3-ux-designer",
    "how-to-keep-up-with-web3-job-market",
    "how-to-land-your-first-web3-job",
    "how-to-make-money-with-web3",
    "how-to-navigate-a-career-in-web3-socialfi-development",
    "how-to-pass-a-solidity-technical-interview",
    "how-to-present-your-web3-portfolio-to-get-noticed",
    "how-to-read-smart-contracts-before-you-ape",
    "how-to-start-a-web3-career",
    "how-to-transition-from-traditional-hr-to-web3-talent-acquisition",
    "how-to-transition-from-web2-to-web3-cybersecurity-specialist",
    "how-to-transition-from-web2-to-web3",
    "how-to-transition-into-web3-with-a-legal-or-compliance-background",
    "how-to-write-a-web3-resume",
    "how-zkevm-brings-zero-knowledge-proofs-to-ethereum",
    "indian-web3-communities",
    "is-a-career-in-web3-right-for-you",
    "is-web3-dead",
    "key-strategies-to-succeed-in-web3-career-interviews",
    "legal-careers-in-web3",
    "most-in-demand-web3-careers",
    "multi-agent-systems-and-ai",
    "navigating-the-metaverse",
    "navigating-the-web3-investment-analyst-career-path",
    "nft-artist-royalties",
    "nft-jobs-explained",
    "on-chain-analyst-job",
    "onboarding-non-technical-talent-in-web3",
    "oracle-use-cases-beyond-price-feeds",
    "remote-web3-jobs",
    "remote-web3-team-playbook",
    "remote-work-in-web3",
    "securing-your-crypto",
    "sidechains-vs-layer-2s",
    "smart-agents-in-ai",
    "smart-contract-auditor-career",
    "smart-contract-jobs",
    "solidity-for-beginners",
    "technical-writer-web3-jobs",
    "the-future-of-decentralized-compute",
    "the-future-of-web3-cross-border-payment-systems-and-jobs",
    "the-future-of-web3-in-digital-rights-and-copyright-protection-jobs",
    "the-future-of-web3-insurance-and-risk-management-jobs",
    "the-growing-demand-for-web3-qa-engineers",
    "the-growing-need-for-web3-blockchain-regulatory-experts",
    "the-most-rewarding-web3-careers",
    "the-rise-of-daos",
    "the-rise-of-the-crypto-native-hr-professional",
    "the-rise-of-the-web3-content-creator",
    "the-rise-of-web3-governance-and-voting-system-engineers",
    "the-role-of-a-tokenomics-designer",
    "the-role-of-a-web3-financial-product-manager",
    "the-role-of-web3-blockchain-performance-optimization-engineers",
    "the-role-of-web3-business-development-professionals",
    "the-role-of-web3-developer-advocates-in-community-building",
    "the-role-of-web3-technical-writers-in-blockchain-projects",
    "the-web3-talent-migration",
    "tokenomics-for-compensation",
    "top-10-web3-developer-skills",
    "top-10-web3-jobs",
    "top-5-web3-languages",
    "top-companies-hiring-for-web3-roles",
    "top-web3-job-opportunities-for-non-developers",
    "understanding-gas-fees-and-optimization-in-ethereum",
    "understanding-multi-party-computation-in-web3",
    "understanding-network-state",
    "understanding-reentrancy-attacks-in-web3-smart-contracts",
    "understanding-the-40-decline-in-blockchain-builder-activity",
    "understanding-tokenomics",
    "understanding-web3-company-culture",
    "understanding-web3-consensus-mechanism-architects",
    "understanding-web3-developer-career-paths",
    "understanding-web3-job-salaries-and-negotiation",
    "web3-and-ai",
    "web3-career-growth-and-development",
    "web3-career-legitimacy",
    "web3-career-salary-negotiation",
    "web3-certifications-and-career-growth",
    "web3-community-manager-career",
    "web3-corporate-structures",
    "web3-customer-support-careers",
    "web3-data-analyst-jobs",
    "web3-developer-portfolio",
    "web3-developer-salaries-2025",
    "web3-for-good-careers-in-social-impact-daos",
    "web3-forensics-and-blockchain-investigators-career-insights",
    "web3-gaming-guilds",
    "web3-go-to-market-playbook",
    "web3-interview-questions",
    "web3-jobs-and-regulatory-unknown",
    "web3-jobs-for-beginners",
    "web3-market-maturation",
    "web3-marketing-jobs",
    "web3-marketing",
    "web3-product-design-careers-for-blockchain-based-apps",
    "web3-product-manager-jobs",
    "web3-product-manager-roadmap",
    "web3-recruiter-tips",
    "web3-salary-negotiation",
    "web3-security-best-practices",
    "web3-social-graph-explained",
    "web3-supply-chain-experts-navigating-blockchain-solutions",
    "web3-talent-migration",
    "web3-trends-2025",
    "web3-ux-design",
    "web3-vc-jobs",
    "what-are-nfts",
    "what-are-oracles",
    "what-are-smart-contracts",
    "what-is-a-blockchain",
    "what-is-a-dao",
    "what-is-a-degen-in-web3",
    "what-is-a-layer-1-blockchain",
    "what-is-a-protocol",
    "what-is-a-web3-devrel-engineer",
    "what-is-a-web3-governance-lead",
    "what-is-a-web3-qa-engineer",
    "what-is-apeing-in-crypto",
    "what-is-arbitrum-one",
    "what-is-avalanche",
    "what-is-defi",
    "what-is-desci",
    "what-is-dyor-in-crypto",
    "what-is-ethereum",
    "what-is-gm-in-web3",
    "what-is-hodl-in-crypto",
    "what-is-mev",
    "what-is-shilling-in-crypto",
    "what-is-socialfi",
    "what-is-solana",
    "what-is-wagmi-and-ngmi",
    "what-is-web3",
    "what-is-yield-farming",
    "why-web3-adoption-is-slow",
    "why-web3-has-fastest-growing-job-market",
    "writing-upgradable-smart-contracts-proxies-explained",
    "your-first-subgraph-indexing-blockchain-data-with-the-graph",
    "zero-knowledge-proofs-explained"
  ];
  
  const articleRoutes: MetadataRoute.Sitemap = articleSlugs.map(slug => ({
    url: `${siteUrl}/${slug}`,
    lastModified: new Date(),
    changeFrequency: 'monthly',
    priority: 0.7
  }));

  const staticRoutes: MetadataRoute.Sitemap = [
    {
      url: siteUrl,
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 1,
    },
    {
      url: `${siteUrl}/jobs`,
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.9,
    },
    {
      url: `${siteUrl}/blog`,
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8
    },
    {
      url: `${siteUrl}/news`,
      lastModified: new Date(),
      changeFrequency: 'hourly',
      priority: 0.9,
    },
    {
        url: `${siteUrl}/salary-calculator`,
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.7,
    },
    {
        url: `${siteUrl}/invoice-generator`,
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.7,
    },
    {
        url: `${siteUrl}/resume-builder`,
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.7,
    },
    {
      url: `${siteUrl}/digital-nomad-visas`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${siteUrl}/remote-work-checklist`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${siteUrl}/interview-questions`,
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.9,
    },
    {
      url: `${siteUrl}/web3-career-quiz`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    }
  ];

  return [...staticRoutes, ...articleRoutes];
}
