
import { MetadataRoute } from 'next';
import { interviewData } from '@/lib/interview-questions';

const siteUrl = 'https://hashtagweb3.com';

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const articleSlugs = [
    "10-big-ideas-in-web3-for-2025",
    "10-dos-and-donts-for-web3-resume",
    "10-essential-skills-for-web3",
    "a-day-in-the-life-of-a-defi-quant",
    "a-deep-dive-into-rollups-for-ethereum-scaling",
    "a-guide-to-verifiable-credentials-in-decentralized-identity",
    "account-abstraction-explained",
    "ai-accountability-governance-models",
    "ai-and-web3-engineering-careers",
    "ai-and-web3-hybrid-careers",
    "ai-driven-agency-from-automation-to-autonomy",
    "an-introduction-to-foundry-the-modern-solidity-toolkit",
    "answering-why-web3-crafting-your-personal-narrative-for-interviews",
    "becoming-a-web3-decentralized-storage-expert",
    "becoming-a-web3-digital-content-monetization-specialist",
    "becoming-a-web3-technical-writer",
    "best-web3-jobs-for-non-developers",
    "beyond-the-code",
    "blockchain-developer-roadmap",
    "blockchain-sharding-scalability",
    "bleisure-destinations-perfect-for-remote-workers",
    "breaking-into-blockchain-devops",
    "breaking-into-web3-a-guide-for-non-technical-professionals",
    "breaking-into-web3-game-development-jobs",
    "building-a-career-as-a-web3-blockchain-infrastructure-engineer",
    "building-a-network-for-web3-career-opportunities",
    "building-career-paths-for-web3-privacy-engineers",
    "building-responsible-ai-systems",
    "building-web3-portfolio",
    "building-your-first-dapp-on-solana-with-rust",
    "career-opportunities-for-web3-blockchain-networking-engineers",
    "cbdc",
    "challenges-in-agentic-ai-governance",
    "china-digital-yuan-ecny",
    "closing-the-web3-talent-gap",
    "combining-business-and-leisure-while-working-globally",
    "common-smart-contract-vulnerabilities-explained",
    "common-take-home-assignments-for-web3-developer-roles",
    "creating-dynamic-nfts-a-step-by-step-guide",
    "crypto-etfs-explained",
    "crypto-guide-for-digital-nomads",
    "crypto-journalist-career-guide",
    "crypto-marketing-jobs",
    "crypto-taxes-guide",
    "decentralized-identity-explained",
    "decoding-web3-salary",
    "does-web3-pay-well",
    "elon-musk-on-web3",
    "entry-level-jobs-in-web3",
    "essential-skills-for-web3-developers",
    "essential-web3-developer-tools",
    "everything-about-externships",
    "exploring-career-opportunities-as-a-web3-blockchain-validator",
    "exploring-career-paths-for-web3-compliance-officers",
    "exploring-careers-in-web3-oracles-and-data-feeds",
    "exploring-cosmos-sdk-for-web3-development",
    "exploring-opportunities-in-web3-real-estate-tokenization",
    "exploring-the-future-of-web3-jobs",
    "exploring-web3-careers-in-decentralized-autonomous-finance",
    "exploring-web3-gaming",
    "exploring-web3-project-manager-career-paths",
    "formal-verification-smart-contract-security",
    "freelance-vs-full-time-web3-career",
    "fresh-graduates-guide-to-crypto-and-web3-jobs",
    "from-side-hustle-to-career",
    "future-of-blockchain-interoperability-with-polkadot",
    "future-of-work-in-the-metaverse",
    "future-of-work-in-web3",
    "gas-optimization-techniques-for-solidity-developers",
    "guide-to-layer-2s",
    "guide-to-stablecoins",
    "hidden-freelance-jobs-that-pay-you-in-crypto",
    "highest-paying-web3-jobs",
    "hiring-for-a-dao",
    "how-dag-based-blockchains-differ-from-traditional-chains",
    "how-formal-verification-improves-smart-contract-security",
    "how-homomorphic-encryption-powers-web3-privacy",
    "how-mev-impacts-web3-networks-and-developers",
    "how-sharding-improves-blockchain-scalability",
    "how-to-be-a-good-community-moderator",
    "how-to-become-a-web3-blockchain-marketing-strategist",
    "how-to-become-a-web3-blockchain-patent-and-ip-expert",
    "how-to-become-a-web3-legal-consultant",
    "how-to-become-a-web3-liquidity-provider-in-decentralized-finance",
    "how-to-become-a-web3-nft-artist",
    "how-to-become-a-web3-smart-contract-developer",
    "how-to-become-a-web3-staking-specialist",
    "how-to-become-a-web3-yield-farming-analyst",
    "how-to-break-into-web3-cryptographic-research-and-development",
    "how-to-break-into-web3-dao-governance-consulting",
    "how-to-break-into-web3-smart-contract-auditing",
    "how-to-build-a-career-as-a-web3-decentralized-exchange-developer",
    "how-to-build-a-long-term-future-in-the-decentralized-world",
    "how-to-build-a-public-on-chain-developer-brand",
    "how-to-build-a-simple-amm-on-an-l2",
    "how-to-build-a-strong-web3-portfolio",
    "how-to-choose-a-crypto-wallet",
    "how-to-cold-contact-and-get-a-response",
    "how-to-contribute-to-daos-and-get-paid",
    "how-to-get-a-high-paying-job-in-web3-as-a-developer",
    "how-to-get-a-job-in-defi-with-no-experience",
    "how-to-get-a-web3-job-with-no-experience",
    "how-to-get-into-web3-cryptocurrency-taxation-and-accounting",
    "how-to-get-started-as-a-web3-cryptocurrency-venture-capital-analyst",
    "how-to-get-started-as-a-web3-nft-marketplace-developer",
    "how-to-get-started-as-a-web3-ux-designer",
    "how-to-keep-up-with-web3-job-market",
    "how-to-land-high-paying-gigs",
    "how-to-make-money-with-web3",
    "how-to-navigate-a-career-in-web3-socialfi-development",
    "how-to-pass-a-solidity-technical-interview",
    "how-to-present-your-web3-portfolio-to-get-noticed",
    "how-to-price-your-services-as-a-freelancer-or-employee",
    "how-to-read-smart-contracts-before-you-ape",
    "how-to-research-a-blockchain-startup",
    "how-to-stand-out-in-crypto-job-interviews",
    "how-to-stay-anonymous-as-a-developer-in-crypto",
    "how-to-survive-a-crypto-bear-market",
    "how-to-transition-from-traditional-hr-to-web3-talent-acquisition",
    "how-to-transition-from-web2-to-web3-cybersecurity-specialist",
    "how-to-transition-into-web3-with-a-legal-or-compliance-background",
    "how-to-write-a-web3-resume",
    "how-zkevm-brings-zero-knowledge-proofs-to-ethereum",
    "indian-web3-communities",
    "is-a-career-in-web3-right-for-you",
    "is-web3-dead",
    "key-strategies-to-succeed-in-web3-career-interviews",
    "legal-careers-in-web3",
    "meaning-of-crypto-and-web3-slangs-and-acronyms",
    "most-demanding-programming-skill",
    "most-in-demand-web3-careers",
    "multi-agent-systems-and-ai",
    "navigating-the-metaverse",
    "navigating-the-web3-investment-analyst-career-path",
    "nft-artist-royalties",
    "nft-jobs-explained",
    "on-chain-analyst-job",
    "on-chain-resume",
    "onboarding-non-technical-talent-in-web3",
    "oracle-use-cases-beyond-price-feeds",
    "remote-web3-jobs",
    "remote-web3-team-playbook",
    "remote-work-in-web3",
    "remote-work-strategies-every-digital-nomad-should-know",
    "securing-your-crypto",
    "sidechains-vs-layer-2s",
    "simple-trick-to-get-crypto-job",
    "smart-agents-in-ai",
    "smart-contract-auditor-career",
    "smart-contract-jobs",
    "solidity-for-beginners",
    "solving-token-compensation-for-web3-employment",
    "technical-writer-web3-jobs",
    "the-best-web3-job-boards-to-kickstart-your-crypto-career",
    "the-future-of-decentralized-compute",
    "the-future-of-web3-cross-border-payment-systems-and-jobs",
    "the-future-of-web3-in-digital-rights-and-copyright-protection-jobs",
    "the-future-of-web3-insurance-and-risk-management-jobs",
    "the-growing-demand-for-web3-qa-engineers",
    "the-growing-need-for-web3-blockchain-regulatory-experts",
    "the-most-rewarding-web3-careers",
    "the-rise-of-daos",
    "the-rise-of-the-crypto-native-hr-professional",
    "the-rise-of-the-web3-content-creator",
    "the-rise-of-web3-governance-and-voting-system-engineers",
    "the-role-of-a-tokenomics-designer",
    "the-role-of-a-web3-financial-product-manager",
    "the-role-of-web3-blockchain-performance-optimization-engineers",
    "the-role-of-web3-business-development-professionals",
    "the-role-of-web3-developer-advocates-in-community-building",
    "the-role-of-web3-technical-writers-in-blockchain-projects",
    "the-secret-to-landing-high-paying-web3-jobs",
    "the-ultimate-packing-list-for-digital-nomads-working-in-tech",
    "the-web3-talent-migration",
    "tokenomics-for-compensation",
    "top-10-crypto-friendly-countries",
    "top-10-web3-developer-skills",
    "top-10-web3-jobs",
    "top-5-web3-languages",
    "top-companies-hiring-for-web3-roles",
    "top-opportunities-in-web3-for-crypto-native-talent",
    "top-skills-employers-are-looking-for-in-web3-developers",
    "understanding-gas-fees-and-optimization-in-ethereum",
    "understanding-multi-party-computation-in-web3",
    "understanding-network-state",
    "understanding-reentrancy-attacks-in-web3-smart-contracts",
    "understanding-the-40-decline-in-blockchain-builder-activity",
    "understanding-tokenomics",
    "understanding-web3-company-culture",
    "understanding-web3-consensus-mechanism-architects",
    "understanding-web3-developer-career-paths",
    "understanding-web3-job-salaries-and-negotiation",
    "web3-and-ai",
    "web3-business-development-career-guide",
    "web3-career-growth-and-development",
    "web3-career-legitimacy",
    "web3-career-salary-negotiation",
    "web3-careers-explained",
    "web3-certifications-and-career-growth",
    "web3-community-manager-career",
    "web3-corporate-structures",
    "web3-customer-support-careers",
    "web3-data-analyst-jobs",
    "web3-developer-portfolio",
    "web3-developer-salaries-2025",
    "web3-for-good-careers-in-social-impact-daos",
    "web3-forensics-and-blockchain-investigators-career-insights",
    "web3-gaming-guilds",
    "web3-go-to-market-playbook",
    "web3-internship-101",
    "web3-interview-questions",
    "web3-jobs-and-regulatory-unknown",
    "web3-jobs-for-beginners",
    "web3-jobs-in-abidjan",
    "web3-jobs-in-accra",
    "web3-jobs-in-addis-ababa",
    "web3-jobs-in-ahmedabad",
    "web3-jobs-in-algiers",
    "web3-jobs-in-antananarivo",
    "web3-jobs-in-argentina",
    "web3-jobs-in-atlanta",
    "web3-jobs-in-austin",
    "web3-jobs-in-australia",
    "web3-jobs-in-bamako",
    "web3-jobs-in-bangalore",
    "web3-jobs-in-bangui",
    "web3-jobs-in-banjul",
    "web3-jobs-in-bissau",
    "web3-jobs-in-boston",
    "web3-jobs-in-brazil",
    "web3-jobs-in-brazzaville",
    "web3-jobs-in-cairo",
    "web3-jobs-in-canada",
    "web3-jobs-in-cape-town",
    "web3-jobs-in-casablanca",
    "web3-jobs-in-chennai",
    "web3-jobs-in-chicago",
    "web3-jobs-in-conakry",
    "web3-jobs-in-dakar",
    "web3-jobs-in-dar-es-salaam",
    "web3-jobs-in-delhi-ncr",
    "web3-jobs-in-denver",
    "web3-jobs-in-djibouti",
    "web3-jobs-in-france",
    "web3-jobs-in-freetown",
    "web3-jobs-in-gaborone",
    "web3-jobs-in-germany",
    "web3-jobs-in-harare",
    "web3-jobs-in-hong-kong",
    "web3-jobs-in-hyderabad",
    "web3-jobs-in-india",
    "web3-jobs-in-indonesia",
    "web3-jobs-in-jaipur",
    "web3-jobs-in-japan",
    "web3-jobs-in-johannesburg",
    "web3-jobs-in-kampala",
    "web3-jobs-in-kigali",
    "web3-jobs-in-kinshasa",
    "web3-jobs-in-kochi",
    "web3-jobs-in-kolkata",
    "web3-jobs-in-lagos",
    "web3-jobs-in-libreville",
    "web3-jobs-in-lilongwe",
    "web3-jobs-in-lome",
    "web3-jobs-in-los-angeles",
    "web3-jobs-in-luanda",
    "web3-jobs-in-lusaka",
    "web3-jobs-in-malabo",
    "web3-jobs-in-maputo",
    "web3-jobs-in-miami",
    "web3-jobs-in-monrovia",
    "web3-jobs-in-mumbai",
    "web3-jobs-in-nairobi",
    "web3-jobs-in-new-york",
    "web3-jobs-in-nigeria",
    "web3-jobs-in-philippines",
    "web3-jobs-in-port-louis",
    "web3-jobs-in-pretoria",
    "web3-jobs-in-pune",
    "web3-jobs-in-rabat",
    "web3-jobs-in-russia",
    "web3-jobs-in-san-francisco",
    "web3-jobs-in-seattle",
    "web3-jobs-in-singapore",
    "web3-jobs-in-south-africa",
    "web3-jobs-in-south-korea",
    "web3-jobs-in-tripoli",
    "web3-jobs-in-tunis",
    "web3-jobs-in-turkey",
    "web3-jobs-in-uae",
    "web3-jobs-in-uk",
    "web3-jobs-in-usa",
    "web3-jobs-in-vietnam",
    "web3-jobs-in-windhoek",
    "web3-market-maturation",
    "web3-marketing-jobs",
    "web3-marketing",
    "web3-product-design-careers-for-blockchain-based-apps",
    "web3-product-manager-jobs",
    "web3-product-manager-roadmap",
    "web3-recruiter-tips",
    "web3-salary-negotiation",
    "web3-security-best-practices",
    "web3-social-graph-explained",
    "web3-supply-chain-experts-navigating-blockchain-solutions",
    "web3-trends-2025",
    "web3-ux-design",
    "web3-vc-jobs",
    "what-are-nfts",
    "what-are-oracles",
    "what-are-smart-contracts",
    "what-is-a-blockchain",
    "what-is-a-dao",
    "what-is-a-degen-in-web3",
    "what-is-a-layer-1-blockchain",
    "what-is-a-protocol",
    "what-is-a-web3-devrel-engineer",
    "what-is-a-web3-governance-lead",
    "what-is-a-web3-qa-engineer",
    "what-is-apeing-in-crypto",
    "what-is-arbitrum-one",
    "what-is-avalanche",
    "what-is-defi",
    "what-is-desci",
    "what-is-dyor-in-crypto",
    "what-is-ethereum",
    "what-is-gm-in-web3",
    "what-is-hodl-in-crypto",
    "what-is-mev",
    "what-is-shilling-in-crypto",
    "what-is-socialfi",
    "what-is-solana",
    "what-is-wagmi-and-ngmi",
    "what-is-web3",
    "what-is-yield-farming",
    "what-makes-a-good-candidate-in-crypto",
    "what-web3-skills-will-matter-in-2026",
    "why-bleisure-travel-is-the-future-of-work-flexibility",
    "why-now-is-the-best-time-to-jobseek-in-crypto",
    "why-web3-adoption-is-slow",
    "why-web3-has-fastest-growing-job-market",
    "writing-upgradable-smart-contracts-proxies-explained",
    "your-first-subgraph-indexing-blockchain-data-with-the-graph",
    "zero-knowledge-proofs-explained",
  ];
  
  const articleRoutes: MetadataRoute.Sitemap = articleSlugs.map(slug => ({
    url: `${siteUrl}/${slug}`,
    lastModified: new Date(),
    changeFrequency: 'monthly',
    priority: 0.7
  }));

  const interviewQuestionRoutes: MetadataRoute.Sitemap = interviewData.roles.map(role => ({
    url: `${siteUrl}/interview-questions#${role.id}`,
    lastModified: new Date(),
    changeFrequency: 'weekly',
    priority: 0.9,
  }));
  
  interviewQuestionRoutes.push({
    url: `${siteUrl}/interview-questions#appendix-a`,
    lastModified: new Date(),
    changeFrequency: 'weekly',
    priority: 0.9,
  }, {
    url: `${siteUrl}/interview-questions#appendix-b`,
    lastModified: new Date(),
    changeFrequency: 'weekly',
    priority: 0.9,
  });

  const staticRoutes: MetadataRoute.Sitemap = [
    {
      url: siteUrl,
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 1,
    },
    {
      url: `${siteUrl}/jobs`,
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 1.0,
    },
    {
      url: `${siteUrl}/blog`,
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8
    },
    {
      url: `${siteUrl}/news`,
      lastModified: new Date(),
      changeFrequency: 'hourly',
      priority: 0.9,
    },
    {
        url: `${siteUrl}/salary-calculator`,
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
    },
    {
        url: `${siteUrl}/invoice-generator`,
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
    },
    {
        url: `${siteUrl}/resume-builder`,
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
    },
    {
        url: `${siteUrl}/jd-builder`,
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
    },
    {
      url: `${siteUrl}/digital-nomad-visas`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: `${siteUrl}/remote-work-checklist`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: `${siteUrl}/interview-questions`,
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.9,
    },
    {
      url: `${siteUrl}/web3-career-quiz`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: `${siteUrl}/employee-onboarding-checklist`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
     {
      url: `${siteUrl}/offer-letter-customizer`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: `${siteUrl}/employee-exit-survey`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: `${siteUrl}/interview-feedback-template`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: `${siteUrl}/employee-milestones-tracker`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: `${siteUrl}/employee-engagement-survey`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: `${siteUrl}/work-life-balance-survey`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: `${siteUrl}/company-culture-guide`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    }
  ];

  return [...staticRoutes, ...articleRoutes, ...interviewQuestionRoutes];
}
