import fs from 'node:fs';
import path from 'node:path';
import { buildGoogleEventSchema, getGoogleEventSchemaIssues } from '../src/lib/event-schema';
import { getEventSlug, type Web3Event } from '../src/lib/events';
import { resolveEventOgImageUrl } from '../src/lib/event-og-url';

const root = process.cwd();
const events = JSON.parse(fs.readFileSync(path.join(root, 'content/events-runtime.json'), 'utf8')) as Web3Event[];
const counts: Record<string, number> = {};
let eligible = 0;
const rows = events.map((event) => {
  const issues = getGoogleEventSchemaIssues(event);
  for (const issue of issues) counts[issue] = (counts[issue] || 0) + 1;
  const url = `https://hashtagweb3.com/${getEventSlug(event)}`;
  const schema = buildGoogleEventSchema(event, { pageUrl: url, imageUrl: event.coverImage ? resolveEventOgImageUrl(event) : undefined });
  if (schema) eligible++;
  if (schema && (!schema.name || !schema.startDate || !schema.location.address)) throw new Error(`Incomplete schema for ${event.id}`);
  return { id: event.id, name: event.name, url, eligible: !!schema, issues, missingRecommended: [
    ...(!event.description ? ['description'] : []), ...(!event.coverImage ? ['image'] : []),
    ...(!schema?.offers ? ['offers'] : []), ...(!schema?.organizer ? ['organizer'] : []),
  ] };
});
const lines = [
  '# Google Event schema audit', '',
  'Generated by `npm run audit:event-schema` against `content/events-runtime.json`.', '',
  '[Google Event documentation](https://developers.google.com/search/docs/appearance/structured-data/event)', '',
  `${eligible} of ${events.length} upcoming event pages meet the local eligibility checks.`, '',
  'Eligible pages emit Event JSON-LD on their individual detail URL. Online-only events, restricted registration, and missing or hidden street addresses do not receive Google Event markup. These events remain available in the directory.', '',
  'Only source-stated prices, currencies, availability, status, and organizer details are included. Recommended fields can remain absent when the source does not provide them. Passing these checks is not a guarantee of a Google rich result.', '',
  '## Exclusions', '', '| Reason | Pages |', '| --- | --- |',
  ...Object.entries(counts).map(([reason, count]) => `| ${reason} | ${count} |`), '',
  '## Pages requiring attention or excluded by Google policy', '', '| Event | Reasons |', '| --- | --- |',
  ...rows.filter((row) => !row.eligible).map((row) => `| [${row.name.replace(/[\[\]|\r\n]/g, ' ')}](${row.url}) | ${row.issues.join(', ')} |`), '',
];
fs.writeFileSync(path.join(root, 'content/events/SCHEMA.md'), lines.join('\n'));
fs.writeFileSync(path.join(root, 'content/events/schema-report.json'), `${JSON.stringify({ total: events.length, eligible, exclusions: counts, events: rows }, null, 2)}\n`);
console.log(`Google Event schema audit: ${eligible}/${events.length} eligible. Exclusions: ${JSON.stringify(counts)}`);
