import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { EVENT_SOURCES } from '../src/lib/event-sources';
import { buildEditorialFromOrganizerDescription, isLumaListedEvent } from '../src/lib/luma-event-content';
import { isThinEventListingDescription } from '../src/lib/event-editorial-facts';
import { getVerifiedEventDescription } from '../src/lib/event-description-source';

function tableText(text: string): string {
  return text.replace(/\|/g, '\\|').replace(/[\r\n]+/g, ' ').replace(/[\[\]<>]/g, '').trim();
}

export function writeEventContentCatalog(check = false): void {
  const index = [
    '# Event description index',
    '',
    'Generated by `npm run organize:events`. Edit the records in `sources/`, then regenerate.',
    '',
    'Each entry links to its formatted description and original source file. All stored records are included, including past events and overlapping feeds.',
    '',
  ];
  const descriptions = [
    '# Stored event descriptions',
    '',
    '[Browse the index](INDEX.md) · [Storage and update guide](README.md)',
    '',
    'Generated from `sources/`. Formatting uses the event-page organizer-copy formatter. Original descriptions remain in the source JSON files.',
    '',
  ];
  let total = 0;
  let luma = 0;
  let missing = 0;

  for (const source of EVENT_SOURCES) {
    const events = [...source.events].sort((a, b) => a.startDate.localeCompare(b.startDate) || a.id.localeCompare(b.id));
    index.push(`## ${source.file}`, '', `${events.length} records. [Source JSON](sources/${source.file})`, '', '| Event | Date | Description |', '| --- | --- | --- |');
    const seen = new Set<string>();
    for (const event of events) {
      if (seen.has(event.id)) throw new Error(`Duplicate id ${event.id} in ${source.file}`);
      seen.add(event.id);
      total++;
      if (isLumaListedEvent(event)) luma++;
      const raw = event.description || '';
      const verifiedDescription = getVerifiedEventDescription(event);
      const thin = isThinEventListingDescription(raw);
      const status = verifiedDescription ? 'Source-backed' : !raw.trim() ? 'Missing' : thin ? 'Listing stub' : 'Unverified stored copy';
      if (thin) missing++;
      const anchor = `event-${createHash('sha256').update(`${source.file}:${event.id}`).digest('hex').slice(0, 16)}`;
      index.push(`| [${tableText(event.name)}](descriptions.md#${anchor}) | ${event.startDate.slice(0, 10)} | ${status} (${raw.length} chars) |`);
      descriptions.push(
        `<a id="${anchor}"></a>`, '', `## ${tableText(event.name)}`, '',
        `- Record: \`${event.id}\``,
        `- Source: [${source.file}](sources/${source.file})`,
        `- Starts: ${event.startDate}`,
        `- Description: ${status}`,
      );
      for (const url of new Set([event.url, event.registrationUrl, event.website].filter(Boolean))) {
        if (/^https?:\/\//i.test(url!)) descriptions.push(`- Original page: <${url}>`);
      }
      descriptions.push('');
      if (!verifiedDescription) {
        descriptions.push('An organizer description has not been verified for this record. Any previous copy is retained in the source JSON for review.', '');
      } else {
        for (const section of buildEditorialFromOrganizerDescription(event).sections) {
          descriptions.push(`### ${section.heading}`, '', ...section.content.flatMap((paragraph) => [paragraph, '']));
        }
      }
    }
    index.push('');
  }
  index.splice(6, 0, `${total} records across ${EVENT_SOURCES.length} feeds; ${luma} Luma-listed records; ${missing} missing descriptions or listing stubs.`, '');
  const outputs = { 'INDEX.md': index.join('\n'), 'descriptions.md': descriptions.join('\n') };
  for (const [file, content] of Object.entries(outputs)) {
    const filePath = path.join(process.cwd(), 'content/events', file);
    const expected = `${content.trimEnd()}\n`;
    if (check) {
      if (!fs.existsSync(filePath) || fs.readFileSync(filePath, 'utf8') !== expected) {
        throw new Error(`${filePath} is stale. Run npm run organize:events.`);
      }
    } else {
      fs.writeFileSync(filePath, expected);
    }
  }
  console.log(`${check ? 'Verified' : 'Organized'} ${total} event descriptions (${luma} Luma-listed; ${missing} missing/stub) in content/events/`);
}
